version: '3.1'
deploy:
  resources:
    limits:
      memory: 4096M
    reservations:
      memory: 2048M
services:
  database:
    container_name: sandbox
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'